# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/rerost/es-cli
    steps:
      - checkout
      - run: make build
    environment:
      GO111MODULE: "on"
  test:
    docker:
      - image: circleci/golang:1.12
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
        environment:
          http.host: '0.0.0.0'
          http.port: 6800
    working_directory: /go/src/github.com/rerost/es-cli
    steps:
      - checkout
      - setup_remote_docker
      - run: make test
      - run: bash <(curl -s https://codecov.io/bash)
    environment:
      GO111MODULE: "on"
  release:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/rerost/es-cli
    steps:
      - checkout
      - run: GOOS=linux   GOARCH=amd64 make build
      - run: GOOS=windows GOARCH=amd64 make build
      - run: GOOS=darwin  GOARCH=amd64 make build
      - run: GOOS=linux   GOARCH=386   make build
      - run: GOOS=windows GOARCH=386   make build
      - run: GOOS=darwin  GOARCH=386   make build
      - run: make release
    environment:
      GO111MODULE: "on"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          context: codecov-es-cli
          requires:
            - build
      - release:
          requires:
            - build
            - test
          filters:
            branches:
              only: /^v\d+\.\d+\.\d+$/
