#!/bin/bash
set -eo pipefail

function exec_only()
{
  cmd="go run main.go --port $1 "

  ## Index
  echo "# list index"
  eval "${cmd} list index" > /dev/null
  echo "# create index"
  eval "${cmd} create index test '{}'" > /dev/null
  echo "# copy index"
  eval "${cmd} copy index test test_copy" > /dev/null
  echo "# count index"
  eval "${cmd} count index test" > /dev/null
  echo "# delete index"
  eval "${cmd} delete index test"
  eval "${cmd} delete index test_copy"

  ## detail
  echo "# update detail"
  eval "${cmd} create index test '{}'" > /dev/null
  eval "${cmd} add alias alias_test test" > /dev/null
  eval "${cmd} update detail alias_test '{}'" > /dev/null

  ## Alias
  echo "# add alias"
  eval "${cmd} create index test1 '{}'" > /dev/null
  eval "${cmd} create index test2 '{}'" > /dev/null
  eval "${cmd} add alias test_alias test1 test2" > /dev/null
  echo "# remove alias"
  eval "${cmd} remove alias test_alias test1 test2" > /dev/null

  ## Tasks
  echo "# list task"
  eval "${cmd} list task" > /dev/null
  echo "# get task"
}

ports=('6500')
for port in ${ports[@]}
do
  exec_only $port
done
